# Generated by Django 6.0.3 on 2026-03-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessontime",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (30, "30 минут"),
                    (60, "1 час"),
                    (90, "1 час 30 минут"),
                    (120, "2 часа"),
                ],
                default=60,
                verbose_name="Продолжительность (минуты)",
            ),
        ),
    ]
