# Generated by Django 6.0.3 on 2026-03-23 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_lessontime_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lessontime",
            index=models.Index(
                fields=["instructor", "datetime"], name="schedule_le_instruc_50042d_idx"
            ),
        ),
    ]
