# Generated by Django 6.0.3 on 2026-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_lessontime_schedule_le_instruc_50042d_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessontime",
            name="attended",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="Посетил занятие"
            ),
        ),
    ]
